# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SegundaTela.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SegundaJanela(object):
    def setupUi(self, SegundaJanela):
        SegundaJanela.setObjectName("SegundaJanela")
        SegundaJanela.resize(750, 379)
        SegundaJanela.setMinimumSize(QtCore.QSize(750, 261))
        SegundaJanela.setMaximumSize(QtCore.QSize(750, 158693))
        SegundaJanela.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/bagla.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SegundaJanela.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(SegundaJanela)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(SegundaJanela)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.labelTexto = QtWidgets.QLabel(self.widget)
        self.labelTexto.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTexto.setObjectName("labelTexto")
        self.gridLayout.addWidget(self.labelTexto, 2, 0, 1, 1)
        self.labelTitulo = QtWidgets.QLabel(self.widget)
        self.labelTitulo.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTitulo.setObjectName("labelTitulo")
        self.gridLayout.addWidget(self.labelTitulo, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 1, 1, 2)
        self.ImagemBagla = QtWidgets.QLabel(SegundaJanela)
        self.ImagemBagla.setText("")
        self.ImagemBagla.setPixmap(QtGui.QPixmap(":/newPrefix/bagla.png"))
        self.ImagemBagla.setScaledContents(False)
        self.ImagemBagla.setObjectName("ImagemBagla")
        self.gridLayout_2.addWidget(self.ImagemBagla, 0, 0, 1, 1)
        self.botaoSim = QtWidgets.QPushButton(SegundaJanela)
        self.botaoSim.setObjectName("botaoSim")
        self.gridLayout_2.addWidget(self.botaoSim, 1, 2, 1, 1)

        self.retranslateUi(SegundaJanela)
        QtCore.QMetaObject.connectSlotsByName(SegundaJanela)

    def retranslateUi(self, SegundaJanela):
        _translate = QtCore.QCoreApplication.translate
        SegundaJanela.setWindowTitle(_translate("SegundaJanela", "Aqui é bagla!"))
        self.labelTexto.setText(_translate("SegundaJanela", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Okay, aceito seu pedido de rendição.</span></p><p align=\"center\"><span style=\" font-size:10pt;\"><br/></span></p><p align=\"center\"><span style=\" font-size:10pt;\">Mas para você conseguir fechar essa janela, <br/>então precisaremos realizar um Puzzle com você, <br/>você topa? <br/><br/>(É, eu sei, você não tem muita escolha)</span></p></body></html>"))
        self.labelTitulo.setText(_translate("SegundaJanela", "<html><head/><body><p><span style=\" font-size:16pt;\">Bagla Puzzle</span></p></body></html>"))
        self.botaoSim.setText(_translate("SegundaJanela", "Sim"))
import Resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SegundaJanela = QtWidgets.QWidget()
    ui = Ui_SegundaJanela()
    ui.setupUi(SegundaJanela)
    SegundaJanela.show()
    sys.exit(app.exec_())
