# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TerceiraTela.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TerceiraJanela(object):
    def setupUi(self, TerceiraJanela):
        TerceiraJanela.setObjectName("TerceiraJanela")
        TerceiraJanela.resize(750, 379)
        TerceiraJanela.setMinimumSize(QtCore.QSize(750, 261))
        TerceiraJanela.setMaximumSize(QtCore.QSize(750, 158693))
        TerceiraJanela.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/bagla.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TerceiraJanela.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(TerceiraJanela)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(TerceiraJanela)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.botaoOpcao2 = QtWidgets.QPushButton(self.widget)
        self.botaoOpcao2.setObjectName("botaoOpcao2")
        self.gridLayout.addWidget(self.botaoOpcao2, 5, 0, 1, 1)
        self.botaoOpcao3 = QtWidgets.QPushButton(self.widget)
        self.botaoOpcao3.setObjectName("botaoOpcao3")
        self.gridLayout.addWidget(self.botaoOpcao3, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.labelTitulo = QtWidgets.QLabel(self.widget)
        self.labelTitulo.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTitulo.setObjectName("labelTitulo")
        self.gridLayout.addWidget(self.labelTitulo, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.botaoOpcao1 = QtWidgets.QPushButton(self.widget)
        self.botaoOpcao1.setObjectName("botaoOpcao1")
        self.gridLayout.addWidget(self.botaoOpcao1, 4, 0, 1, 1)
        self.labelTexto = QtWidgets.QLabel(self.widget)
        self.labelTexto.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTexto.setObjectName("labelTexto")
        self.gridLayout.addWidget(self.labelTexto, 2, 0, 1, 1)
        self.botaoOpcao4 = QtWidgets.QPushButton(self.widget)
        self.botaoOpcao4.setObjectName("botaoOpcao4")
        self.gridLayout.addWidget(self.botaoOpcao4, 7, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 1, 1, 5)
        self.ImagemBagla = QtWidgets.QLabel(TerceiraJanela)
        self.ImagemBagla.setText("")
        self.ImagemBagla.setPixmap(QtGui.QPixmap(":/newPrefix/bagla.png"))
        self.ImagemBagla.setScaledContents(False)
        self.ImagemBagla.setObjectName("ImagemBagla")
        self.gridLayout_2.addWidget(self.ImagemBagla, 0, 0, 1, 1)

        self.retranslateUi(TerceiraJanela)
        QtCore.QMetaObject.connectSlotsByName(TerceiraJanela)

    def retranslateUi(self, TerceiraJanela):
        _translate = QtCore.QCoreApplication.translate
        TerceiraJanela.setWindowTitle(_translate("TerceiraJanela", "Aqui é bagla!"))
        self.botaoOpcao2.setText(_translate("TerceiraJanela", "Bagla"))
        self.botaoOpcao3.setText(_translate("TerceiraJanela", "Eu sou idiota"))
        self.labelTitulo.setText(_translate("TerceiraJanela", "<html><head/><body><p><span style=\" font-size:16pt;\">Pergunta 1 / 145</span></p></body></html>"))
        self.botaoOpcao1.setText(_translate("TerceiraJanela", "Não Faz Sentido"))
        self.labelTexto.setText(_translate("TerceiraJanela", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Qual é a primeira palavra que </span></p><p align=\"center\"><span style=\" font-size:10pt;\">o Filipe Neto disse em seu primeiro </span></p><p align=\"center\"><span style=\" font-size:10pt;\">video no Youtube?</span></p></body></html>"))
        self.botaoOpcao4.setText(_translate("TerceiraJanela", "Ele não falou nada nesse video"))
import Resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TerceiraJanela = QtWidgets.QWidget()
    ui = Ui_TerceiraJanela()
    ui.setupUi(TerceiraJanela)
    TerceiraJanela.show()
    sys.exit(app.exec_())
