# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UltimaTela.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UltimaJanela(object):
    def setupUi(self, UltimaJanela):
        UltimaJanela.setObjectName("UltimaJanela")
        UltimaJanela.resize(484, 473)
        UltimaJanela.setMinimumSize(QtCore.QSize(484, 473))
        UltimaJanela.setMaximumSize(QtCore.QSize(484, 473))
        UltimaJanela.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/bagla.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UltimaJanela.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(UltimaJanela)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(UltimaJanela)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.labelTitulo = QtWidgets.QLabel(self.widget)
        self.labelTitulo.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTitulo.setObjectName("labelTitulo")
        self.gridLayout.addWidget(self.labelTitulo, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.widgetButtons = QtWidgets.QWidget(self.widget)
        self.widgetButtons.setMinimumSize(QtCore.QSize(80, 250))
        self.widgetButtons.setObjectName("widgetButtons")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widgetButtons)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.widgetButtons)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/loader.gif"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 3, 1, 1)
        self.gridLayout.addWidget(self.widgetButtons, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 6)
        self.botaoFinalizar = QtWidgets.QPushButton(UltimaJanela)
        self.botaoFinalizar.setMinimumSize(QtCore.QSize(100, 0))
        self.botaoFinalizar.setObjectName("botaoFinalizar")
        self.gridLayout_2.addWidget(self.botaoFinalizar, 1, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(UltimaJanela)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 2, 1, 1)
        self.labelTentativas = QtWidgets.QLabel(UltimaJanela)
        self.labelTentativas.setObjectName("labelTentativas")
        self.gridLayout_2.addWidget(self.labelTentativas, 1, 1, 1, 1)
        self.labelMinimizadas = QtWidgets.QLabel(UltimaJanela)
        self.labelMinimizadas.setObjectName("labelMinimizadas")
        self.gridLayout_2.addWidget(self.labelMinimizadas, 1, 3, 1, 1)

        self.retranslateUi(UltimaJanela)
        QtCore.QMetaObject.connectSlotsByName(UltimaJanela)

    def retranslateUi(self, UltimaJanela):
        _translate = QtCore.QCoreApplication.translate
        UltimaJanela.setWindowTitle(_translate("UltimaJanela", "Aqui é bagla!"))
        self.labelTitulo.setText(_translate("UltimaJanela", "<html><head/><body><p><span style=\" font-size:16pt;\">VOCÊ BAGLOU!</span></p></body></html>"))
        self.botaoFinalizar.setText(_translate("UltimaJanela", "Finalizar"))
        self.labelTentativas.setText(_translate("UltimaJanela", "Tentativas: "))
        self.labelMinimizadas.setText(_translate("UltimaJanela", "Minimizadas:"))
import Resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UltimaJanela = QtWidgets.QWidget()
    ui = Ui_UltimaJanela()
    ui.setupUi(UltimaJanela)
    UltimaJanela.show()
    sys.exit(app.exec_())
